version: "3.8"

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=debt_solve
      - DB_SSLMODE=disable
      - JWT_SECRET=DebtSolver
      - JWT_EXPIRATION_HOURS=24
    ports:
      - "8080:8080"
