name: "Build and Push Docker Image with version"

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Define Date and Time Tag
      - name: Define Image Date Tag
        id: vars
        run: |
          DATE_TAG=$(date +'%Y%m%d-%H%M')
          echo "DATE_TAG=${DATE_TAG}" >> $GITHUB_ENV
          echo "IMAGE_NAME=billzhaohongwei/caa900debtsolverproject:auth-service" >> $GITHUB_ENV

      # Step 5: Build Docker Image with both latest and date tags
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${DATE_TAG} .

      # Step 6: Push Docker Images with both tags
      - name: Push Docker Images
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${DATE_TAG}
