name: Cleanup Old Docker Images

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub and Retrieve Token
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d '{"username": "'"${{ secrets.DOCKER_USERNAME }}"'", "password": "'"${{ secrets.DOCKER_PASSWORD }}"'"}' \
            "https://hub.docker.com/v2/users/login/")
          
          TOKEN=$(echo "$RESPONSE" | jq -r '.token')
          
          if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
            echo "Error: Unable to retrieve Docker Hub token. Response: $RESPONSE"
            exit 1
          fi
          
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Debug Docker Hub Token
        run: echo "Docker Hub Token: ${{ env.TOKEN }}"

      - name: List All Image Tags
        run: |
          RESPONSE=$(curl -s -H "Authorization: JWT ${{ env.TOKEN }}" \
            "https://hub.docker.com/v2/repositories/billzhaohongwei/caa900debtsolverproject-auth-service/tags/?page_size=100")
          
          echo "Tags API Response: $RESPONSE"

          TAGS=$(echo "$RESPONSE" | jq -r '.results | sort_by(.last_updated) | .[].name')
          if [ -z "$TAGS" ]; then
            echo "No tags found or error retrieving tags."
            exit 1
          fi

          echo "$TAGS" > tags.txt
